python train_whisper_supervised.py --architecture-name openai/whisper-tiny \
                                   --checkpoint-dir-root ./checkpoints \
                                   --use-pretrained-whisper-encoder \
                                   --use-pretrained-whisper-decoder \
                                   --clotho-dir ../data/clotho_v2.1 \
                                   --audioset-dir ../data/audioset \
                                   --num-dev-examples-to-log-preds 3 \
                                   --num-val-examples-to-log-preds 3 \
                                   --log-preds-every-n-steps 3 \
                                   --limit-dev-split-size 5 \
                                   --limit-val-split-size 5 \
                                   --training-args-config ../configs/train_whisper_supervised_train_args.yaml